import '../globals.css'
import type { Metadata } from 'next'
import ClientSide from '../components/ClientSide'
import NavbarRemoteDesktop from './components/NavbarRemoteDesktop'

export const metadata: Metadata = {
    title: 'Remote Desktop Ui',
    description: 'Generated by Leopico',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            <ClientSide>
                <NavbarRemoteDesktop />
            </ClientSide>
            <div>
                {children}
            </div>
        </>
    )
}
