import '../globals.css'
import type { Metadata } from 'next'
import ClientSide from '../components/ClientSide'
import NavbarBlogPage from './components/NavbarBlogPage'

export const metadata: Metadata = {
    title: 'Blog Page Ui',
    description: 'Generated by Leopico',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode

}) {
    return (
        <div className='bg-[#121927] '>
            <ClientSide>
                <NavbarBlogPage />
            </ClientSide>
            <div>
                {children}
            </div>
        </div>
    )
}
