import '../globals.css'
import type { Metadata } from 'next'
import ClientSide from '../components/ClientSide'

export const metadata: Metadata = {
    title: 'Timeline Page Ui',
    description: 'Generated by Leopico',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            {children}
        </>
    )
}
