import { Inter } from 'next/font/google'
import '../globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Countdown Ui',
    description: 'Generated by Leopico',
}


export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className='font-primary'>
            {children}
        </div>
    )
}
