import '../globals.css'
import type { Metadata } from 'next'
import ClientSide from '../components/ClientSide'
import NavbarLadingPage from './components/NavbarLadingPage'

export const metadata: Metadata = {
    title: 'Landing Page Ui',
    description: 'Generated by Leopico',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            <ClientSide>
                <NavbarLadingPage />
            </ClientSide>
            <div>
                {children}
            </div>
        </>
    )
}
